dataset: oxford_spires
raw_data_root: /media/jcy/6f8bd02b-5080-9f4b-ad42-598fc747eda6/datasets_for_lingbot_map/oxford_spires_dataset
sampling:
  strategy: sequence
  stride: 12
evaluation:
  depth:
    gt_clip:
      min: 0.0
      max: 200.0
  points:
    icp_threshold: 0.5
